modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs_mekanism&mc=2101&loader=neoforge"
license = "MIT"

[[mods]]
modId = "kubejs_mekanism"
version = "${version}"
displayName = "KubeJS Mekanism"
authors = "latvian.dev"
description = '''
KubeJS Mekanism integration
'''
logoFile = "kubejs_mekanism_logo.png"
modUrl = "https://kubejs.com"
displayURL = "https://kubejs.com"

[[dependencies.kubejs_mekanism]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_mekanism]]
modId = "mekanism"
mandatory = true
versionRange = "[${mekanism_version},)"
ordering = "AFTER"
side = "BOTH"